spring:
  liquibase:
    enabled: true
    change-log: liquibase/db.master.xml
  datasource:
    username: mvideoUser
    password: mvideoPass
    url: jdbc:postgresql://192.168.0.109:5432/mvideo
    driver-class-name: org.postgresql.Driver
server:
  port: 8088
